### ISSUE TITLE
Supporting Genocide is inhumanity

### ISSUE THREAD

**Issue by alaminkawsar** [Augus1999/pyPDFeditor-GUI#6]
Hey, Do you support genocide against Gaza?

![Screenshot from 2024-10-26 10-51-52](https://github.com/user-attachments/assets/33bae0b0-aca7-4f9b-a779-90789d5b9bd6)

**Comment by Augus1999** [comment]
My friend if you find it's an issue, I'm sorry I cannot do anything about it.
